### ISSUE TITLE
material-camera

### ISSUE THREAD

**Issue by pjebs** [pln-fing-udelar/pghumor#3]
Hi there.

I was wondering if you can tell me how to add your fork: `https://github.com/xmartlabs/material-camera/tree/feature/camera-changes` from camera-changes branch to gradle.

I can't get it to work. Is there anything that you can do to make it work - register it with Mavern etc?

How do you incorporate it. I tried `jitpack` but it doesn't work.

Please forgive that I wrote the message here because your materical camera fork doesn't permit creating issues.

**Comment by pjebs** [comment]
@rammadogs

**Comment by bryant1410** [comment]
You should add:

```groovy
compile "com.github.xmartlabs:material-camera:ae1292a"
```

If the fork doesn't allow issues, you should have written me an email, or Xmartlabs.

**Comment by pjebs** [comment]
Thank you. We couldn't find your email address. I do believe @rammadogs (my colleague) did write to your company though.

**Comment by pjebs** [comment]
Is that material library still a good library because the upstream repo seems to not be maintained anymore.

**Comment by bryant1410** [comment]
yeah, it still is, we fixed some issues but we are not actively maintaining it
